### ISSUE TITLE
[Req] Syntax for GENERATED BY DEFAULT AS IDENTITY

### ISSUE THREAD

**Issue by ArsenShnurkov** [deveel/deveeldb#121]
SQL 2011, part 2, paragraph 11.4, "column definition"

    <identity column specification> ::=
    GENERATED { ALWAYS | BY DEFAULT } AS IDENTITY
    [ <left paren> <common sequence generator options> <right paren> ]

see also
SQL 2011, part 2, paragraph 4.15.11, Identity columns

my example:

    CREATE TABLE mytable (k INTEGER GENERATED BY DEFAULT AS IDENTITY, v VARCHAR);

This is not a question on how to replace it with something non-standard. It is the request for implementing the standard syntax.

**Comment by tsutomi** [comment]
The dialect DeveelDB is developing supports this case already, but not according to the standard of SQL-2011: instead of defining a data type for the column, one must specify the `IDENTITY` type, that is a shortcut to `NUMERIC DEFAULT UNIQUEKEY('table_name')`

``` sql
CREATE TABLE test (id IDENTITY, name VARCHAR(50))
```

is equivalent to

``` sql
CREATE TABLE test (id NUMERIC NOT NULL DEFAULT UNIQUEKEY('test'), name VARCHAR(50))
```
