### ISSUE TITLE
[mono] Command 'IF NOT EXIST ...' exited with code: 126

### ISSUE THREAD

**Issue by ArsenShnurkov** [deveel/deveeldb#122]
this code doesn't work on linux:

https://github.com/deveel/deveeldb/blob/b135cfc0fea4698d76ce8b87ed95928a5a3f0584/src/deveeldb/deveeldb.csproj#L978-L980

/usr/lib64/mono/4.5/Microsoft.Common.targets: Error: Command 'IF NOT EXIST "/var/calculate/remote/distfiles/egit-src/deveeldb.git/src/../dist/AnyCPU" MKDIR "/var/calculate/remote/distfiles/egit-src/deveeldb.git/src/../dist/AnyCPU"
/var/calculate/remote/distfiles/egit-src/deveeldb.git/src/../util/ilrepack/ILRepack.exe /internalize /targetplatform:v2 /xmldocs /out:"/var/calculate/remote/distfiles/egit-src/deveeldb.git/src/../dist/AnyCPU/deveeldb.dll" "/var/calculate/remote/distfiles/egit-src/deveeldb.git/src/deveeldb/bin/Release//deveeldb.dll" "/var/calculate/remote/distfiles/egit-src/deveeldb.git/src/deveeldb/bin/Release//irony.dll" "/var/calculate/remote/distfiles/egit-src/deveeldb.git/src/deveeldb/bin/Release//Deveel.Math.dll" "/var/calculate/remote/distfiles/egit-src/deveeldb.git/src/deveeldb/bin/Release//DryIoc.dll"' exited with code: 126. (deveeldb)

- mkdir is lowercase command
- the syntax for directory checking is different for bash
- I think, that ILRepack.exe (rogue local binary on my system!) should be run with mono prefix and from system-defined path

I saw this on Release and Release|x64 configurations

I propose (to someone) to rewrite this post-build fragment in platform-independent way.

**Comment by ArsenShnurkov** [comment]
<a href="https://msdn.microsoft.com/en-us/library/s2448zz7.aspx">MakeDir Task</a>,
<a href="https://msdn.microsoft.com/en-us/library/3e54c37h.aspx">Copy Task</a>

**Comment by tsutomi** [comment]
I agree @ArsenShnurkov  that the build should be platform independent and to operate on the MSBuild tasks.
I used the command line tool for DOS for brevity and speed, and also because it was easier to write, but the build should be modified to use those tasks.

**Comment by tsutomi** [comment]
I moved the whole merge process into the CI machine ( https://ci.appveyor.com/project/Deveel/deveeldb ) through a script, and removed all the commands for merging from the projects
