### ISSUE TITLE
Parsing errors are not visible in NUnit logs

### ISSUE THREAD

**Issue by ArsenShnurkov** [deveel/deveeldb#128]
typical parsing error looks like this:
<pre>Deveel.Data.Client.DeveelDbException : Error when selecting a scalar value.
  ----> Deveel.Data.Client.DeveelDbException : An error occurred while executing a query.
  ----> System.Runtime.Remoting.ServerException : Exception of type 'Deveel.Data.Sql.Parser.SqlParseException' was thrown.</pre>

it contain no nested exceptions and details.

it's antipattern:
https://en.wikipedia.org/wiki/Error_hiding

and this is the location where it occurs:
https://github.com/ArsenShnurkov/deveeldb/blob/test-code/src/deveeldb/Deveel.Data.Sql.Statements/SqlStatement.cs#L172
https://github.com/ArsenShnurkov/deveeldb/blob/test-code/src/deveeldb/Deveel.Data.Protocol/ClientConnector.cs#L96

see the screenshot - https://github.com/deveel/deveeldb/pull/129

**Comment by ArsenShnurkov** [comment]
a improved message:   ----> System.Runtime.Remoting.ServerException : SqlParseException for SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES;
Level: Error, Line: 0, Column: 13, Message: A parse error occurred near 'SELECT COUNT ( * ' in the source. Expected simple_id, :, string, number, TRUE, FALSE, NULL, (, NOT, +, -, ~, CASE, SELECT, )

**Comment by tsutomi** [comment]
Most likely this is a missing rule in the SQL parser grammar, that doesn't recognize the glob character as a valid one as function argument.
I will write a parse test case for it.

**Comment by tsutomi** [comment]
The new Compile mechanism now provides several set of *Message* objects, together with the return statements. Messages can be *Warning*, *Syntax Error* or *Unhandled Error* types.
Probably in a future release we will also include "Debug", to support the *4 levels of compilation messages*
