### ISSUE TITLE
Infer SQL Type from Values

### ISSUE THREAD

**Issue by tsutomi** [deveel/deveeldb#130]
When executing a SQL statement, a user might pass a value that is not immediately compatible with the value of a table column or a type attribute.
The idea is to verify if the input value can be converted to the destination type without throwing exceptions and do it automatically to keep the process light

**Comment by ArsenShnurkov** [comment]
function evaluation doesn't executed:
http://arsenshnurkov.github.io/linux-sharp/DeveelDB/type-conversion-bug.htm

**Comment by ArsenShnurkov** [comment]
2004-04, Type inference in sql, http://spectrum.library.concordia.ca/7920/1/MQ91069.pdf

**Comment by tsutomi** [comment]
Ana analysis of the test revealed an error in the parsing code, that was adding a new expression value to the values in the tuple: in fact, it was adding the function call AND the argument of the function call as values to be inserted.

**Comment by tsutomi** [comment]
Inferring of SQL Types from values is not happening in every operation that involves writing into tables and executing routines (that is, all the operations where a given SQL Type is given). 
We might want some more fine grained inferring (eg. dynamically defined types), but for the moment this case can be considered closed
