### ISSUE TITLE
Make SQL Parsing Optional

### ISSUE THREAD

**Issue by tsutomi** [deveel/deveeldb#165]
As much as ANTLRv4 SQL Parser for DeveelDB is a fast component and quite reliable, it comes with great size (both for generated files and ANTLR runtime library): in some small contexts, the size of the application becomes and important factor to be able to work.

Making the SQL parsing optional and using LINQ-to-Embedded DeveelDB  can still provide query features as for the full version, cutting off 30-40% of its size

**Comment by ArsenShnurkov** [comment]
%)

**Comment by tsutomi** [comment]
@ArsenShnurkov the SQL string parsing is already optional in fact: you can build any statement programmatically, in a Roslyn-style.
The fact is that SELECT statements are still too complex not to parse them (although it is possible to create them using SqlQueryExpression and/or SelectStatement): the introduction of LINQ embedded in the kernel would transform object queries to SQL queries, removing the constraint of the parser.

**Comment by ArsenShnurkov** [comment]
I found one more parser. Pliant it's name, Marpa algorithm implementation on C#
https://github.com/patrickhuber/Pliant

i think it is more situable than antlr because it is pure C#

**Comment by tsutomi** [comment]
I have redesigned the system to use the service registration from the Context of execution to resolve implementations of `ISqlParser` (as much as `ISqlTypeParser` and `ISqlExpressionParser`).

This allows the implementation of parser that implement the Contracts and use them within the DeveelDB system.
A default implementation is done using ANTLR4, that proves being very fast and easy to work with, although it doesn't allow the generation of private classes
