### ISSUE TITLE
Trigger Body

### ISSUE THREAD

**Issue by tsutomi** [deveel/deveeldb#34]
Triggers are currently implemented in two different forms:
* Callback Triggers - They notify external listeners of an event on a table (INSERT, DELETE, UPDATE)
* Procedure Trigger - They execute a given procedure before or after the event

In case of the ''Procedure Trigger'' there is no possibility to define a body of the execution, but just reference an existing procedure.

It must be possible for the user to define the body of the routine to execute on the trigger itself.

**Comment by win32nipuh** [comment]
Probably the word 'TRIGGER' should be added to the reserved words list?

**Comment by tsutomi** [comment]
Actually, in the version 2.0 I'm going to use a totally new SQL parser (based on a version of Irony, modified by me), discontinuing completely CSharpCC and its generated parser.
In the new version, _TRIGGER_ is a reserved word, as for the ANSI SQL92 standard.

**Comment by win32nipuh** [comment]
ok.
Why you are using Irony? 
It is good tool, but it does not generate separate lexer and parser. 
I.e. in any case you need to use Irony assemblies.

I researched some parser generation tools.
Why not something like LLLPG? it can generate both parser types: including assemblies and separate files (including some LLLPG sources).

**Comment by tsutomi** [comment]
Actually, I've done some experiments with ANTLR (both v3 and v4) and I tried to pursue the original CSharpCC model, but a fellow gave me some examples of Irony SQL parsing grammar that looked good.
I contacted the LLLPG author to get some support in the creation of the SQL parser, since the grammar looked so much different from the standards, but he was unsupportive, so I gave up, since Irony was already doing what I wanted with brilliant performances.
I agree it's a bit painful to write your own AST (the new parsing process goes through this model), but after all it's a little price to pay for control: Irony provides an EBNF logic that is easy to cope with and the fact it's 100% .NET based makes it easy to discover code errors ahead of time.
The new library also uses ILMerge to create the final assembly, merging Deveel.Math library and Irony: the footprint of the Irony runtime is quite small, so it's not a big price to pay.

Anyway, if you have some good experience with LLLPG and you're able to write a PL/SQL parser/lexer, it would be great if you'd help me writing a parser and eventually evaluate its complexity.

**Comment by win32nipuh** [comment]
I see.
By the way, I asked LLLPG's author some time ago about SQL Parser here  :-)

http://www.codeproject.com/Articles/664785/A-New-Parser-Generator-for-Csharp

See messages:
"What about SQL?"

**Comment by tsutomi** [comment]
I see your comment to the article and the reply of the author: SQL EBNF is not hard (even with PL/SQL dialect) to parse indeed. The real issue is to convert the EBNF notation (derived from the ANSI standards) into a concrete parser: LLLPG requires an higher learning curve and has not any community around it to support. Irony at the contrary can let you define a more EBNF-like syntax, plus it has a little community behind (parser generators are meta-tools, with not much usage, and every one makes a very little niche).

**Comment by tsutomi** [comment]
Trigger body has been defined and supported on programmatic level: to support also the parsing support on SQL I will open a new issue, if needed
