### ISSUE TITLE
Fluid Query Builder

### ISSUE THREAD

**Issue by tsutomi** [deveel/deveeldb#95]
Provide a builder that allows the creation in code of SQL Queries, instead of going through strings or complex SQL Expressions

**Comment by meikeric** [comment]
Why not just build an Entity Framework 7 provider? For non-embedded installations, this seems more logical.

**Comment by tsutomi** [comment]
@meikeric  I developed a LINQ provider already, but as an external tool. A provider for EF is also a good idea as contributed project.

The scope of this issue is to provide a _fluid_ interface for building complex queries within DeveelDB core library itself, or for those applications embedding it. Nothing too advanced, but to take out the string building outside the process (that is prone to typos and makes difficult debugging).
This requirement emerged from the fact that the `CREATE VIEW ...` statements inside DeveeldB (for the _INFORMATION_SCHEMA_ ) are all built using strings, and in a certain moment it became difficult to track the errors: in fact, building a view from code is still a hard job

**Comment by tsutomi** [comment]
This idea is getting outdated from the case #148
