### ISSUE TITLE
Scattered File-Based Storage

### ISSUE THREAD

**Issue by tsutomi** [deveel/deveeldb#96]
Implement a strong file-based storage system that can be scaled on big data sizes, scattering files with this order:
- One file per table of the database
- Maximum size of 2Gb per file, after which create a connected file for the same table

**Comment by meikeric** [comment]
If you're interested, I've done some implementation code of a inverted column store.  Re: [https://en.wikipedia.org/wiki/Inverted_index](url).  Let me know if you'd like to discuss.

**Comment by tsutomi** [comment]
Hi @meikeric ! I would definitively like to discuss this with you. At the moment, I have an implementation of a file-based inverted index storage system for DeveelDB that is under review in a branch of the project (the implementation is finished, but tests fail, and I don't want to affect the current state).

Your solution might be more interesting and better designed (still haven't seen the code, so hard to judge :+1:  ) and I would like to see if we can create a IStorageSystem based on it: the architecture of DeveelDB allows to have multiple storage systems, even within the same infrastructure (but one storage system per database).

You can join the conversation on Gitter or reach me in the Slack domain of Deveel (both links in the ReadMe of the project, here in GitHub)

**Comment by meikeric** [comment]
Let me know when you have time and I'll hop on Gitter and detail some of my thoughts for you.

**Comment by tsutomi** [comment]
The new file-based storage system has been implemented, and supports journaling (logging) and scattering of files.
We can consider other file-system storage systems in a future version of the library
